on: push
name: build and test app
jobs:
  build:
    name: install dependencies
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1

    - name: install dependencies
      uses: steebchen/flutter@v1.1.0
      with:
        args: pub get

    - name: build apk
      uses: steebchen/flutter@v1.1.0
      with:
        args: build apk --target-platform android-arm,android-arm64,android-x64 --split-per-abi
        
